/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import codes.DBconnection;

import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;

import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.Connection;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;

import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


/**
 *
 * @author minuri senara
 */
public class billing extends javax.swing.JFrame {

    /**
     * Creates new form billing
     */
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rst = null;
    public billing() {
        initComponents();
        conn = DBconnection.connect();
    }

    public void search(){
    String see = searchbox.getText();
        try {
            String sql  = "SELECT * FROM  patients WHERE name= '"+see+"'  ";
            pst = conn.prepareStatement(sql);
            rst=pst.executeQuery();
            while(rst.next()){
              
                    numberbox.setText(String.format("0"+rst.getString("contact")));
                    SimpleDateFormat myformat = new SimpleDateFormat("yyyy-MM-dd");    
                    java.sql.Date day = rst.getDate("addmissiondate");
                    daofaddbox.setDate(day);
     
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
}
    
    public void quantity(){
        try {
            SimpleDateFormat myformat = new SimpleDateFormat("yyyy-MM-dd");
        Date d1 =  daofaddbox.getDate();
        
        Date d2 =  dofbillbox1.getDate();
        long different = d2.getTime() - d1.getTime();
        long stay = different/(1000*60*60*24);
        q1box.setText(Long.toString(stay));
        q2box.setText(Long.toString(stay));
        q3box.setText(Long.toString(stay));
        q4box.setText(Long.toString(stay));
            int z = 6;
        q5box.setText(Integer.toHexString(z));
        q6box.setText(Long.toString(stay));
        
         
   
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
 
    }
    
    public void unite(){
        
        u1box.setText(Integer.toString((int) 1800.00));
      
        u3box.setText(Integer.toString((int) 1200.00));
      
        u5box.setText(Integer.toString((int) 3500.00));
       
    }
    
    public void cost(){
        int u1 = Integer.parseInt(u1box.getText());
        int q1 = Integer.parseInt(q1box.getText());
        int cost1 = u1*q1;
        c1box.setText(Integer.toString(cost1));
        int u3 = Integer.parseInt(u3box.getText());
        int q3 = Integer.parseInt(q3box.getText());
        int cost2 = u3*q3;
        c3box.setText(Integer.toString(cost2));
        int u5 = Integer.parseInt(u5box.getText());
        int q5 = Integer.parseInt(q5box.getText());
        int cost5 = u5*q5;
        c5box.setText(Integer.toString(cost5));
        
        
            
           
 
        
    }
    
    public void total(){
          int c1 = Integer.parseInt(c1box.getText());
        int c2 = Integer.parseInt(c2box.getText());
        int c3 = Integer.parseInt(c3box.getText());
        int c4 = Integer.parseInt(c4box.getText());
        int c5 = Integer.parseInt(c5box.getText());
        int c6 = Integer.parseInt(c6box.getText());
        
        String c11 = c1box.getText();
        String c22 = c2box.getText();
        String c33 = c3box.getText();
        String c44 = c4box.getText();
        String c55 = c5box.getText();
        String c66 = c6box.getText(); 
        
        if(c11.equals("") || c22.equals("") || c33.equals("") || c44.equals("") || c55.equals("") || c66.equals("")){
            JOptionPane.showMessageDialog(null,"try");
        }
        
      
        
       
             
             int total = c1+c2+c3+c4+c5+c6;
             totalbox.setText("LKR."+Integer.toString(total)+".00");
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        numberbox = new javax.swing.JTextField();
        searchbox = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        u1box = new javax.swing.JTextField();
        q2box = new javax.swing.JTextField();
        q1box = new javax.swing.JTextField();
        q3box = new javax.swing.JTextField();
        q4box = new javax.swing.JTextField();
        q5box = new javax.swing.JTextField();
        q6box = new javax.swing.JTextField();
        u3box = new javax.swing.JTextField();
        u5box = new javax.swing.JTextField();
        c1box = new javax.swing.JTextField();
        c2box = new javax.swing.JTextField();
        c3box = new javax.swing.JTextField();
        c4box = new javax.swing.JTextField();
        c5box = new javax.swing.JTextField();
        c6box = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jPanel29 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jPanel30 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        totalbox = new javax.swing.JTextField();
        jPanel31 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        dofbillbox1 = new com.toedter.calendar.JDateChooser();
        daofaddbox = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(105, 135));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(197, 226, 238));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(37, 171, 226));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sd.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 0, 30, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Contact Number");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Search By Patient Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, -1, -1));

        numberbox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        numberbox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numberbox.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        numberbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberboxActionPerformed(evt);
            }
        });
        jPanel1.add(numberbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 160, 40));

        searchbox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        searchbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchboxActionPerformed(evt);
            }
        });
        searchbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchboxKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchboxKeyReleased(evt);
            }
        });
        jPanel1.add(searchbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 210, 40));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/12.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 50, 40, 40));

        jPanel3.setBackground(new java.awt.Color(37, 171, 226));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("CLEAR");
        jButton6.setContentAreaFilled(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 50, 80, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Date Of Billing");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 120, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Date Of Admission");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, -1, -1));

        u1box.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        u1box.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        u1box.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(u1box, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 130, 30));

        q2box.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        q2box.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        q2box.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(q2box, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 70, 30));

        q1box.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        q1box.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        q1box.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(q1box, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 70, 30));

        q3box.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        q3box.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        q3box.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(q3box, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 70, 30));

        q4box.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        q4box.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        q4box.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(q4box, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 70, 30));

        q5box.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        q5box.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        q5box.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(q5box, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, 70, 30));

        q6box.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        q6box.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        q6box.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(q6box, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 450, 70, 30));

        u3box.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        u3box.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        u3box.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(u3box, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, 130, 30));

        u5box.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        u5box.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        u5box.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(u5box, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 410, 130, 30));

        c1box.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        c1box.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c1box.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(c1box, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 250, 160, 30));

        c2box.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        c2box.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c2box.setText("0");
        c2box.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(c2box, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 290, 160, 30));

        c3box.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        c3box.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c3box.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(c3box, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 330, 160, 30));

        c4box.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        c4box.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c4box.setText("0");
        c4box.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(c4box, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 370, 160, 30));

        c5box.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        c5box.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c5box.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(c5box, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 410, 160, 30));

        c6box.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        c6box.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c6box.setText("0");
        c6box.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        c6box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c6boxActionPerformed(evt);
            }
        });
        jPanel1.add(c6box, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 450, 160, 30));

        jPanel4.setBackground(new java.awt.Color(37, 171, 226));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TOTAL");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, 190, 50));

        jPanel5.setBackground(new java.awt.Color(37, 171, 226));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Quantity");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 150, 30));

        jPanel6.setBackground(new java.awt.Color(37, 171, 226));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Unit Price");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel14)
                .addContainerGap(113, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 230, 30));

        jPanel7.setBackground(new java.awt.Color(37, 171, 226));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Cost");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel15)
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 210, 160, 30));

        jPanel8.setBackground(new java.awt.Color(37, 171, 226));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Description");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel16)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, 30));

        jPanel9.setBackground(new java.awt.Color(0, 153, 255));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Bed Charges");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel30)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 190, -1));

        jPanel26.setBackground(new java.awt.Color(0, 153, 255));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Helper");

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel31)
                .addContainerGap(124, Short.MAX_VALUE))
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 190, -1));

        jPanel27.setBackground(new java.awt.Color(0, 153, 255));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Food And Beverages");

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel27Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel32)
                .addGap(29, 29, 29))
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 190, -1));

        jPanel28.setBackground(new java.awt.Color(0, 153, 255));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Drugs ( Western )");

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel28Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel33)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 190, -1));

        jPanel29.setBackground(new java.awt.Color(0, 153, 255));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Physiotherapist");

        javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(jPanel29);
        jPanel29.setLayout(jPanel29Layout);
        jPanel29Layout.setHorizontalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel29Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel34)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel29Layout.setVerticalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 190, -1));

        jPanel30.setBackground(new java.awt.Color(0, 153, 255));

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Other");

        javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel30Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel35)
                .addContainerGap(132, Short.MAX_VALUE))
        );
        jPanel30Layout.setVerticalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 190, -1));

        totalbox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        totalbox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalbox.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(totalbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, 570, 51));

        jPanel31.setBackground(new java.awt.Color(0, 153, 255));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("1.SET Details");
        jButton4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("2. TOTAL");
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setText("3. BILLING");
        jButton5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel31Layout = new javax.swing.GroupLayout(jPanel31);
        jPanel31.setLayout(jPanel31Layout);
        jPanel31Layout.setHorizontalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel31Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31))
        );
        jPanel31Layout.setVerticalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel31Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 210, 170, 330));

        jButton11.setText("EDIT");
        jButton11.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 250, 60, 30));

        jButton12.setText("EDIT");
        jButton12.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 330, 60, 30));

        jButton13.setText("EDIT");
        jButton13.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 410, 60, 30));
        jPanel1.add(dofbillbox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 140, 160, 40));
        jPanel1.add(daofaddbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 160, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void clear(){
     searchbox.setText("");
        numberbox.setText("");
        daofaddbox.setDate(null);
        dofbillbox1.setDate(null);
        q1box.setText("");
        q2box.setText("");
        q3box.setText("");
        q4box.setText(""); 
        q5box.setText("");
        q6box.setText("");
        u1box.setText("");
        u3box.setText("");
        u5box.setText("");
        c1box.setText("");
        c2box.setText("0");
        c3box.setText("");
        c4box.setText("0");
        c5box.setText("");
        c6box.setText("0");
        totalbox.setText("");
        
        
}
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
clear();
       
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    }//GEN-LAST:event_jButton2ActionPerformed

    private void searchboxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchboxKeyReleased
search();
    }//GEN-LAST:event_searchboxKeyReleased

    private void searchboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchboxKeyPressed
search();
    }//GEN-LAST:event_searchboxKeyPressed

    private void searchboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchboxActionPerformed

    private void numberboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberboxActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    quantity();
    unite();
   cost();
  
    }//GEN-LAST:event_jButton4ActionPerformed

    private void dofbillbox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dofbillbox1MouseClicked
       
    }//GEN-LAST:event_dofbillbox1MouseClicked

    private void dofbillbox1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dofbillbox1MouseReleased
      
    }//GEN-LAST:event_dofbillbox1MouseReleased

    private void dofbillbox1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dofbillbox1KeyPressed
    
    }//GEN-LAST:event_dofbillbox1KeyPressed

    private void dofbillbox1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dofbillbox1MouseEntered
         // TODO add your handling code here:
    }//GEN-LAST:event_dofbillbox1MouseEntered

    private void dofbillbox1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dofbillbox1MouseExited
   
    }//GEN-LAST:event_dofbillbox1MouseExited

    private void dofbillbox1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dofbillbox1MousePressed
      
    }//GEN-LAST:event_dofbillbox1MousePressed

    private void dofbillbox1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dofbillbox1KeyReleased
         
    }//GEN-LAST:event_dofbillbox1KeyReleased

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       SimpleDateFormat myformat = new SimpleDateFormat("yyyy-MM-dd");
        String name = searchbox.getText();
       int contact = Integer.parseInt(numberbox.getText());
       Date addday1 = daofaddbox.getDate();
       String addday = myformat.format(addday1);
       Date billdate1 = dofbillbox1.getDate();
       String billdate = myformat.format(billdate1);
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
          File path = chooser.getSelectedFile();
      
       
       com.itextpdf.text.Document doc = new com.itextpdf.text.Document();
        try {
            PdfWriter.getInstance(doc,new FileOutputStream(path+".pdf"));
                    
            doc.open();
            Paragraph paragraph1 = new Paragraph("THE   HELPING   HAND   PSYCHOLOGICAL   HOSPITAL");
            doc.add(paragraph1);
            Paragraph paragraph2 = new Paragraph("*************************************************************************************************");
            doc.add(paragraph2);
            Paragraph paragraph3 = new Paragraph("INVOICE\n" + "The Helping Hand\n" +"Psychological Hospital &\n" +"Research Center");
            doc.add(paragraph3);
            doc.add(paragraph2);
            Paragraph paragraph5 = new Paragraph("\tPatient Name : "+ name + "\nDate Of Admission : "+addday+ "\nDate Of Billing : "+billdate + "\nContact Number : 0"+contact);
            doc.add(paragraph5);
            doc.add(paragraph2);
            Paragraph paragraph15 = new Paragraph("                                           ");
            doc.add(paragraph15);
            doc.add(paragraph15);
            PdfPTable tb1 = new PdfPTable(4);
          
            tb1.addCell("Description");
            tb1.addCell("Quantity");
            tb1.addCell("Unit Price");
            tb1.addCell("Cost");
            
            tb1.addCell("Bed Charges");
            String q1 = q1box.getText();
            tb1.addCell(q1);
            String u1 = u1box.getText();
            tb1.addCell("LKR."+u1+".00");
            String c1 = c1box.getText();
            tb1.addCell("LKR."+c1+".00");
            
            tb1.addCell("Helper");
            String q2 = q2box.getText();
            tb1.addCell(q2);
            tb1.addCell(" ");
            String c2 = c2box.getText();
            tb1.addCell("LKR."+c2+".00");
            
            tb1.addCell("Food And Beverages");
            String q3 = q3box.getText();
            tb1.addCell(q3);
            String u3 = u3box.getText();
            tb1.addCell("LKR."+u3+".00");
            String c3 = c3box.getText();
            tb1.addCell("LKR."+c3+".00");
            
            tb1.addCell("Drugs ( Western )");
            String q4 = q4box.getText();
            tb1.addCell(q4);
            tb1.addCell(" ");
            String c4 = c4box.getText();
            tb1.addCell("LKR."+c4+".00");
            
            tb1.addCell("Physiotherapist");
            String q5 = q5box.getText();
            tb1.addCell(q5);
            String u5 = u5box.getText();
            tb1.addCell("LKR."+u5+".00");
            String c5 = c5box.getText();
            tb1.addCell("LKR."+c5+".00");
            
            tb1.addCell("Other");
            String q6 = q6box.getText();
            tb1.addCell(q6);
            tb1.addCell(" ");
            String c6 = c6box.getText();
            tb1.addCell("LKR."+c6+".00");
            
            String total = totalbox.getText();
            PdfPCell cell = new PdfPCell(new Paragraph("                                                                                   Total : "+total));
            cell.setColspan(4);
            tb1.addCell(cell);
            doc.add(tb1);
            Paragraph paragraph12 = new Paragraph("                                           ");
            doc.add(paragraph12);
            doc.add(paragraph12);
            doc.add(paragraph2);
            
            
            Paragraph paragraph10 = new Paragraph("                                           ");
            doc.add(paragraph10);
            
            Paragraph paragraph6 = new Paragraph("No . 386/A/10 Kularathna\n" + "Mawatha, Akkarapanaha ,\n" + "Negombo.No . 386/A/10 Kularathna\n" +"Mawatha, Akkarapanaha ,\n" +"Negombo.");
            doc.add(paragraph6);
            
            
            Paragraph paragraph7 = new Paragraph("Hotline – 011 7561122\n" + "0719001212");
            doc.add(paragraph7);
            doc.add(paragraph10);
            doc.add(paragraph10);
            
            Paragraph paragraph8 = new Paragraph("E-mail - \n" +"thehelpinghand100@\n" +"gmail.com");
            doc.add(paragraph8);
            doc.add(paragraph10);
            
            Paragraph paragraph9 = new Paragraph("Web  –\n" + "www.helpinghandlk.com ");
            doc.add(paragraph9);
            doc.add(paragraph10);
            
            
            
            
            
            
            
            
            
            
            
            
            JOptionPane.showMessageDialog(null,"Bill Genareted");
            setVisible(true);
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
       doc.close();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        total();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        int u1 = Integer.parseInt(u1box.getText());
        int q1 = Integer.parseInt(q1box.getText());
        int z = u1*q1;
        c1box.setText(Integer.toString(z));
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
       int u3 = Integer.parseInt(u3box.getText());
        int q3 = Integer.parseInt(q3box.getText());
        int z = u3*q3;
        c3box.setText(Integer.toString(z));
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        int u1 = Integer.parseInt(u5box.getText());
        int q1 = Integer.parseInt(q5box.getText());
        int z = u1*q1;
        c5box.setText(Integer.toString(z));
    }//GEN-LAST:event_jButton13ActionPerformed

    private void c6boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c6boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c6boxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new billing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField c1box;
    private javax.swing.JTextField c2box;
    private javax.swing.JTextField c3box;
    private javax.swing.JTextField c4box;
    private javax.swing.JTextField c5box;
    private javax.swing.JTextField c6box;
    private com.toedter.calendar.JDateChooser daofaddbox;
    private com.toedter.calendar.JDateChooser dofbillbox1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField numberbox;
    private javax.swing.JTextField q1box;
    private javax.swing.JTextField q2box;
    private javax.swing.JTextField q3box;
    private javax.swing.JTextField q4box;
    private javax.swing.JTextField q5box;
    private javax.swing.JTextField q6box;
    private javax.swing.JTextField searchbox;
    private javax.swing.JTextField totalbox;
    private javax.swing.JTextField u1box;
    private javax.swing.JTextField u3box;
    private javax.swing.JTextField u5box;
    // End of variables declaration//GEN-END:variables
}
